CREATE DATABASE 909803_doingsdone
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;
USE 909803_doingsdone;

CREATE TABLE users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  timezone VARCHAR(100) NOT NULL,
  reg_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE projects (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  author_id INT UNSIGNED NOT NULL,
  FOREIGN KEY (author_id) REFERENCES users (id)
);

CREATE TABLE tasks (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  adding_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deadline DATE,
  is_completed TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  file_link VARCHAR(64),
  file_name VARCHAR(255),
  author_id INT UNSIGNED NOT NULL,
  project_id INT UNSIGNED NOT NULL,
  FOREIGN KEY (author_id) REFERENCES users (id),
  FOREIGN KEY (project_id) REFERENCES projects (id),
  FULLTEXT INDEX title_ft_idx (title)
);
